# 1) Build Stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Production build
RUN npm run build


# 2) Nginx Stage (serve the built files)
FROM nginx:stable-alpine

# Copy production build from previous stage
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 for production
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]