FROM node:22-alpine

WORKDIR /app

# Copy only package.json to install dependencies efficiently
COPY package*.json ./

# Install only production deps
RUN npm install --production

# Copy source code
COPY . .

# Expose app port
EXPOSE 5000

# Run production server
CMD ["npm", "start"]
